#!/usr/bin/env bash
set -euo pipefail

# Generated by `cleo-1 cleo11-launch --emit-script`
# Profile: full  Config: configs/cleo11_135m.toml

docker build -f cloud/cleo11/Dockerfile -t cleo11-pretrain:latest .

docker run --gpus all --rm \
  -v $(pwd)/data/cleo11:/workspace/data/cleo11 \
  -v $(pwd)/artifacts/cleo11:/workspace/artifacts/cleo11 \
  -e CLEO11_PROFILE=full \
  -e CLEO11_CONFIG=configs/cleo11_135m.toml \
  -e CLEO11_NPROC=1 \
  -e CLEO11_PREPARE=1 \
  -e HF_TOKEN="${HF_TOKEN}" \
  cleo11-pretrain:latest
