from __future__ import annotations

from pathlib import Path
from typing import Any


DEFAULT_IMAGE = "cleo11-pretrain:latest"
DEFAULT_CONFIG = "configs/cleo11_135m.toml"


def docker_build_command(*, image: str = DEFAULT_IMAGE, context: str = ".") -> str:
    return f"docker build -f cloud/cleo11/Dockerfile -t {image} {context}"


def docker_run_command(
    *,
    image: str = DEFAULT_IMAGE,
    profile: str = "full",
    config: str = DEFAULT_CONFIG,
    nproc: int = 1,
    prepare: bool = True,
    data_mount: str = "$(pwd)/data/cleo11",
    artifacts_mount: str = "$(pwd)/artifacts/cleo11",
    hf_token_env: str = "${HF_TOKEN}",
    max_steps: int | None = None,
) -> str:
    env_parts = [
        f'-e CLEO11_PROFILE={profile}',
        f'-e CLEO11_CONFIG={config}',
        f'-e CLEO11_NPROC={nproc}',
        f'-e CLEO11_PREPARE={"1" if prepare else "0"}',
        f'-e HF_TOKEN="{hf_token_env}"',
    ]
    if max_steps is not None:
        env_parts.append(f"-e CLEO11_MAX_STEPS={max_steps}")
    envs = " \\\n  ".join(env_parts)
    return (
        f"docker run --gpus all --rm \\\n"
        f"  -v {data_mount}:/workspace/data/cleo11 \\\n"
        f"  -v {artifacts_mount}:/workspace/artifacts/cleo11 \\\n"
        f"  {envs} \\\n"
        f"  {image}"
    )


def torchrun_command(
    *,
    config: str = DEFAULT_CONFIG,
    nproc: int = 1,
    device: str = "cuda",
    max_steps: int | None = None,
    resume: str | None = None,
) -> str:
    overrides = ""
    if max_steps is not None:
        overrides += f" --max-steps {max_steps}"
    if resume:
        overrides += f" --resume {resume}"
    return (
        f"torchrun --standalone --nproc_per_node={nproc} -m cleo1.cleo11.pretrain_entry "
        f"--cleo11-config {config} --device {device}{overrides}"
    )


def emit_launch_plan(
    *,
    profile: str = "full",
    config: str = DEFAULT_CONFIG,
    nproc: int = 1,
    prepare: bool = True,
    image: str = DEFAULT_IMAGE,
    max_steps: int | None = None,
) -> dict[str, Any]:
    build = docker_build_command(image=image)
    run = docker_run_command(
        image=image,
        profile=profile,
        config=config,
        nproc=nproc,
        prepare=prepare,
        max_steps=max_steps,
    )
    native = torchrun_command(config=config, nproc=nproc, max_steps=max_steps)
    return {
        "provider": "docker-torchrun",
        "dry_run": True,
        "profile": profile,
        "config": config,
        "nproc": nproc,
        "commands": {
            "docker_build": build,
            "docker_run": run,
            "native_torchrun": native,
        },
        "notes": [
            "Dry-run only: no cloud credits are spent by cleo11-launch.",
            "Mount prepared shards at /workspace/data/cleo11 or set CLEO11_PREPARE=1 to stream-encode on the GPU VM.",
            "Export HF_TOKEN when preparing from Hugging Face datasets.",
            "Use the M4 for development/eval; run the 135M full pretrain on cloud CUDA GPUs.",
        ],
    }


def write_launch_script(path: str | Path, plan: dict[str, Any]) -> Path:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    commands = plan["commands"]
    script = f"""#!/usr/bin/env bash
set -euo pipefail

# Generated by `cleo-1 cleo11-launch --emit-script`
# Profile: {plan["profile"]}  Config: {plan["config"]}

{commands["docker_build"]}

{commands["docker_run"]}
"""
    destination.write_text(script, encoding="utf-8")
    destination.chmod(destination.stat().st_mode | 0o111)
    return destination
